spring:
# DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
  datasource:
    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost/sample_db?autoReconnect=true&useSSL=false
    url: jdbc:mysql://mydb.c2d6yuy7egrg.us-west-2.rds.amazonaws.com:3306/sample_db
#    url: jdbc:mysql://104.198.126.171:3306/sample_db?autoReconnect=true&useSSL=false

#server.port: 5000
logging.level.org.springframework: WARN